#spring:
#    application:
#        name: api-gateway
#    cloud:
#        gateway:
#            mvc:
#                routes:
#                    - id: VOTER-SERVICE
#                      uri: lb://VOTER-SERVICE
#                      predicates:
#                          - Path=/api/voter/**
#                    - id: CONSTITUENCY-SERVICE
#                      uri: lb://CONSTITUENCY-SERVICE
#                      predicates:
#                          - Path=/api/constituency/**
#
#server:
#    port: 8083
#eureka:
#    instance:
#        ip-address: true
#    client:
#        service-url:
#            default-zone: http://localhost:8761/eureka/
